/**
 * 24k
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AggregationMethods } from '../models/AggregationMethods';
import { Condition } from '../models/Condition';
import { HttpFile } from '../http/http';

export class Aggregation {
    'type': AggregationMethods;
    'field'?: string;
    'filter'?: Array<Condition>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "AggregationMethods",
            "format": ""
        },
        {
            "name": "field",
            "baseName": "field",
            "type": "string",
            "format": ""
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "Array<Condition>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Aggregation.attributeTypeMap;
    }

    public constructor() {
    }
}



