/**
 * 24k
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EntitlementRevision } from '../models/EntitlementRevision';
import { Pricing } from '../models/Pricing';
import { HttpFile } from '../http/http';

export class APIEntitlement {
    /**
    * The ID of the entitlement
    */
    'id': string;
    /**
    * The ID of the account
    */
    'accountId': string;
    /**
    * The ID of the customer
    */
    'customerId': string;
    /**
    * The ID of the product
    */
    'productId': string;
    'pricing': Pricing;
    /**
    * Revisions
    */
    'revisions'?: Array<EntitlementRevision>;
    /**
    * The date the entitlement was assigned
    */
    'assignedAt': Date;
    'createdAt': Date;
    'updatedAt': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "accountId",
            "baseName": "accountId",
            "type": "string",
            "format": ""
        },
        {
            "name": "customerId",
            "baseName": "customerId",
            "type": "string",
            "format": ""
        },
        {
            "name": "productId",
            "baseName": "productId",
            "type": "string",
            "format": ""
        },
        {
            "name": "pricing",
            "baseName": "pricing",
            "type": "Pricing",
            "format": ""
        },
        {
            "name": "revisions",
            "baseName": "revisions",
            "type": "Array<EntitlementRevision>",
            "format": ""
        },
        {
            "name": "assignedAt",
            "baseName": "assignedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return APIEntitlement.attributeTypeMap;
    }

    public constructor() {
    }
}
