/**
 * 24k
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { APIInvoiceBillingPeriod } from '../models/APIInvoiceBillingPeriod';
import { InvoiceProductBreakdown } from '../models/InvoiceProductBreakdown';
import { HttpFile } from '../http/http';

/**
* API Invoice
*/
export class APIInvoice {
    /**
    * ID
    */
    'id': string;
    /**
    * Name
    */
    'name': string;
    /**
    * Account ID
    */
    'accountId': string;
    /**
    * Customer ID
    */
    'customerId': string;
    /**
    * Price Breakdown
    */
    'price': number;
    /**
    * Products ids
    */
    'products': Array<string>;
    /**
    * Price breakdown for each product
    */
    'priceBreakdown': { [key: string]: InvoiceProductBreakdown; };
    'billingPeriod': APIInvoiceBillingPeriod;
    /**
    * Created At
    */
    'createdAt': string;
    /**
    * Updated At
    */
    'updatedAt': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "accountId",
            "baseName": "accountId",
            "type": "string",
            "format": ""
        },
        {
            "name": "customerId",
            "baseName": "customerId",
            "type": "string",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": "double"
        },
        {
            "name": "products",
            "baseName": "products",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "priceBreakdown",
            "baseName": "priceBreakdown",
            "type": "{ [key: string]: InvoiceProductBreakdown; }",
            "format": ""
        },
        {
            "name": "billingPeriod",
            "baseName": "billingPeriod",
            "type": "APIInvoiceBillingPeriod",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string",
            "format": "date"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "string",
            "format": "date"
        }    ];

    static getAttributeTypeMap() {
        return APIInvoice.attributeTypeMap;
    }

    public constructor() {
    }
}

