/**
 * 24k
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class APIIngestEventPayload {
    /**
    * Name
    */
    'eventName': string;
    /**
    * Timestamp - When the event occurred
    */
    'timestamp': number;
    /**
    * Customer Identifier
    */
    'customerAlias': string;
    /**
    * Event Ref
    */
    'ref': string;
    /**
    * Construct a type with a set of properties K of type T
    */
    'data': { [key: string]: any; };

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "eventName",
            "baseName": "eventName",
            "type": "string",
            "format": ""
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "number",
            "format": "double"
        },
        {
            "name": "customerAlias",
            "baseName": "customerAlias",
            "type": "string",
            "format": ""
        },
        {
            "name": "ref",
            "baseName": "ref",
            "type": "string",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "{ [key: string]: any; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return APIIngestEventPayload.attributeTypeMap;
    }

    public constructor() {
    }
}

