/**
 * 24k
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Criterion } from '../models/Criterion';
import { HttpFile } from '../http/http';

export class Condition {
    'criterions': Array<Criterion>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "criterions",
            "baseName": "criterions",
            "type": "Array<Criterion>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Condition.attributeTypeMap;
    }

    public constructor() {
    }
}
