/**
 * 24k
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CriterionOperators } from '../models/CriterionOperators';
import { CriterionValue } from '../models/CriterionValue';
import { HttpFile } from '../http/http';

export class Criterion {
    'value': CriterionValue;
    'operator': CriterionOperators;
    'field': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "value",
            "baseName": "value",
            "type": "CriterionValue",
            "format": ""
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "CriterionOperators",
            "format": ""
        },
        {
            "name": "field",
            "baseName": "field",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Criterion.attributeTypeMap;
    }

    public constructor() {
    }
}



