/**
 * 24k
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Pricing } from '../models/Pricing';
import { HttpFile } from '../http/http';

export class EntitlementRevision {
    /**
    * A class representation of the BSON ObjectId type.
    */
    'revisionId': string;
    'reason': string;
    'asOf': Date;
    'pricing': Pricing;
    'createdAt': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "revisionId",
            "baseName": "revisionId",
            "type": "string",
            "format": ""
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "string",
            "format": ""
        },
        {
            "name": "asOf",
            "baseName": "asOf",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "pricing",
            "baseName": "pricing",
            "type": "Pricing",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return EntitlementRevision.attributeTypeMap;
    }

    public constructor() {
    }
}
