/**
 * 24k
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { APIIngestEventPayload } from '../models/APIIngestEventPayload';
import { HttpFile } from '../http/http';

export class IngestEventToTheSystem201Response {
    'insertedIds': Array<string>;
    'insertedCount': number;
    'payload': Array<APIIngestEventPayload>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "insertedIds",
            "baseName": "insertedIds",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "insertedCount",
            "baseName": "insertedCount",
            "type": "number",
            "format": "double"
        },
        {
            "name": "payload",
            "baseName": "payload",
            "type": "Array<APIIngestEventPayload>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IngestEventToTheSystem201Response.attributeTypeMap;
    }

    public constructor() {
    }
}

