/**
 * 24k
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PricingTiersInner {
    'chunkSize': number;
    'price': number;
    'end': number | null;
    'start': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "chunkSize",
            "baseName": "chunkSize",
            "type": "number",
            "format": "double"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": "double"
        },
        {
            "name": "end",
            "baseName": "end",
            "type": "number",
            "format": "double"
        },
        {
            "name": "start",
            "baseName": "start",
            "type": "number",
            "format": "double"
        }    ];

    static getAttributeTypeMap() {
        return PricingTiersInner.attributeTypeMap;
    }

    public constructor() {
    }
}
