/**
 * 24k
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PricingCadence } from '../models/PricingCadence';
import { PricingTiersInner } from '../models/PricingTiersInner';
import { HttpFile } from '../http/http';

export class Pricing {
    'commitment'?: number;
    'tiers': Array<PricingTiersInner>;
    'cadence'?: PricingCadence;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "commitment",
            "baseName": "commitment",
            "type": "number",
            "format": "double"
        },
        {
            "name": "tiers",
            "baseName": "tiers",
            "type": "Array<PricingTiersInner>",
            "format": ""
        },
        {
            "name": "cadence",
            "baseName": "cadence",
            "type": "PricingCadence",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Pricing.attributeTypeMap;
    }

    public constructor() {
    }
}


