/**
 * 24k
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { APIEvent } from '../models/APIEvent';
import { HttpFile } from '../http/http';

export class QueryResultAPIEvent {
    /**
    * Items
    */
    'items': Array<APIEvent>;
    /**
    * Total items found
    */
    'totalCount': number;
    /**
    * There are more items
    */
    'hasMore': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<APIEvent>",
            "format": ""
        },
        {
            "name": "totalCount",
            "baseName": "totalCount",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "hasMore",
            "baseName": "hasMore",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return QueryResultAPIEvent.attributeTypeMap;
    }

    public constructor() {
    }
}
