/**
 * 24k
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Pricing } from '../models/Pricing';
import { HttpFile } from '../http/http';

export class ReviseProductPayload {
    /**
    * The reason the product was revised
    */
    'reason': string;
    'pricing': Pricing;
    /**
    * The date the revision is effective as of
    */
    'asOf': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "reason",
            "baseName": "reason",
            "type": "string",
            "format": ""
        },
        {
            "name": "pricing",
            "baseName": "pricing",
            "type": "Pricing",
            "format": ""
        },
        {
            "name": "asOf",
            "baseName": "asOf",
            "type": "string",
            "format": "date"
        }    ];

    static getAttributeTypeMap() {
        return ReviseProductPayload.attributeTypeMap;
    }

    public constructor() {
    }
}

