/**
 * Vayu API
 * The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@withvayu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AggregationOperator } from '../models/AggregationOperator';
import { HttpFile } from '../http/http';

/**
* The aggregation method defines how the events should be summed to represent a usage value.
*/
export class AggregationMethod {
    'operator': AggregationOperator;
    /**
    * The field inside the \"data\" property to apply the aggregation method to.
    */
    'field'?: string;
    /**
    * The fields that is used to group different events together when measuring the usage.
    */
    'instanceKey'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "operator",
            "baseName": "operator",
            "type": "AggregationOperator",
            "format": ""
        },
        {
            "name": "field",
            "baseName": "field",
            "type": "string",
            "format": ""
        },
        {
            "name": "instanceKey",
            "baseName": "instanceKey",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AggregationMethod.attributeTypeMap;
    }

    public constructor() {
    }
}


