/**
 * Vayu API
 * The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@withvayu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreateMeasurementRequestUsageDate } from '../models/CreateMeasurementRequestUsageDate';
import { HttpFile } from '../http/http';

export class CreateMeasurementRequest {
    /**
    * The customer for whom usage will be attributed
    */
    'customerId': string;
    /**
    * The meter/product that is being measured
    */
    'meterId': string;
    'usageDate': CreateMeasurementRequestUsageDate;
    /**
    * The updated value of product units consumed by the customer, for the product for given day
    */
    'value': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "customerId",
            "baseName": "customerId",
            "type": "string",
            "format": ""
        },
        {
            "name": "meterId",
            "baseName": "meterId",
            "type": "string",
            "format": ""
        },
        {
            "name": "usageDate",
            "baseName": "usageDate",
            "type": "CreateMeasurementRequestUsageDate",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateMeasurementRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
