/**
 * Vayu API
 * The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@withvayu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EventsDryRunResponseObjectEvent } from '../models/EventsDryRunResponseObjectEvent';
import { EventsDryRunResponseObjectMeterWithValuesInner } from '../models/EventsDryRunResponseObjectMeterWithValuesInner';
import { HttpFile } from '../http/http';

export class EventsDryRunResponseObject {
    'event': EventsDryRunResponseObjectEvent;
    'matchedCustomer'?: string | null;
    'meterWithValues': Array<EventsDryRunResponseObjectMeterWithValuesInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "event",
            "baseName": "event",
            "type": "EventsDryRunResponseObjectEvent",
            "format": ""
        },
        {
            "name": "matchedCustomer",
            "baseName": "matchedCustomer",
            "type": "string",
            "format": ""
        },
        {
            "name": "meterWithValues",
            "baseName": "meterWithValues",
            "type": "Array<EventsDryRunResponseObjectMeterWithValuesInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EventsDryRunResponseObject.attributeTypeMap;
    }

    public constructor() {
    }
}

