/**
 * Vayu API
 * The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@withvayu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FullDayPeriod } from '../models/FullDayPeriod';
import { LineItem } from '../models/LineItem';
import { HttpFile } from '../http/http';

export class GetInvoiceResponseInvoice {
    /**
    * The id of the customer that the invoice is associated with
    */
    'customerId': string;
    /**
    * The id of the contract that the invoice is associated with
    */
    'contractId'?: string;
    /**
    * The name of the invoice, usually a description of the billing period
    */
    'name': string;
    'billingCycle': FullDayPeriod;
    'lineItems': Array<LineItem>;
    /**
    * The total amount of the invoice
    */
    'amount': number;
    'id': string;
    'createdAt': Date;
    'updatedAt': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "customerId",
            "baseName": "customerId",
            "type": "string",
            "format": ""
        },
        {
            "name": "contractId",
            "baseName": "contractId",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "billingCycle",
            "baseName": "billingCycle",
            "type": "FullDayPeriod",
            "format": ""
        },
        {
            "name": "lineItems",
            "baseName": "lineItems",
            "type": "Array<LineItem>",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return GetInvoiceResponseInvoice.attributeTypeMap;
    }

    public constructor() {
    }
}

