/**
 * Vayu API
 * The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@withvayu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NetSuiteSyncInvoicesRequestData } from '../models/NetSuiteSyncInvoicesRequestData';
import { HttpFile } from '../http/http';

export class NetSuiteSyncInvoicesRequest {
    'integrationType': NetSuiteSyncInvoicesRequestIntegrationTypeEnum;
    'uid': string;
    'data': NetSuiteSyncInvoicesRequestData;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "integrationType",
            "baseName": "integrationType",
            "type": "NetSuiteSyncInvoicesRequestIntegrationTypeEnum",
            "format": ""
        },
        {
            "name": "uid",
            "baseName": "uid",
            "type": "string",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "NetSuiteSyncInvoicesRequestData",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NetSuiteSyncInvoicesRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum NetSuiteSyncInvoicesRequestIntegrationTypeEnum {
    UpsertInvoice = 'upsertInvoice'
}

