/**
 * Vayu API
 * The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@withvayu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BillingInterval } from '../models/BillingInterval';
import { PaymentTerm } from '../models/PaymentTerm';
import { HttpFile } from '../http/http';

/**
* The billing data of the plan. The billing data contains the billing interval, the plan duration the payment terms and auto renewal, and the billing method.
*/
export class PlanBillingData {
    'billingInterval': BillingInterval;
    'duration': number;
    'paymentTerm': PaymentTerm;
    'autoRenewal': boolean;
    'proRated': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "billingInterval",
            "baseName": "billingInterval",
            "type": "BillingInterval",
            "format": ""
        },
        {
            "name": "duration",
            "baseName": "duration",
            "type": "number",
            "format": ""
        },
        {
            "name": "paymentTerm",
            "baseName": "paymentTerm",
            "type": "PaymentTerm",
            "format": ""
        },
        {
            "name": "autoRenewal",
            "baseName": "autoRenewal",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "proRated",
            "baseName": "proRated",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PlanBillingData.attributeTypeMap;
    }

    public constructor() {
    }
}



