/**
 * Vayu API
 * The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@withvayu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ProductConsumption {
    /**
    * The id of the product.
    */
    'productId': string;
    /**
    * The name of the product.
    */
    'productName': string;
    /**
    * The amount of units provisioned to the customer.
    */
    'provisionedAmount': number;
    /**
    * The amount of units consumed by the customer.
    */
    'consumedAmount': number;
    /**
    * The percentage of the provisioned amount that has been consumed.
    */
    'usagePercentage': number;
    /**
    * Whether the customer has access to the product.
    */
    'hasAccess': boolean;
    /**
    * The amount of units remaining to consume.
    */
    'remainingAmount'?: number;
    /**
    * The amount of units exceeded.
    */
    'exceededAmount'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "productId",
            "baseName": "productId",
            "type": "string",
            "format": ""
        },
        {
            "name": "productName",
            "baseName": "productName",
            "type": "string",
            "format": ""
        },
        {
            "name": "provisionedAmount",
            "baseName": "provisionedAmount",
            "type": "number",
            "format": ""
        },
        {
            "name": "consumedAmount",
            "baseName": "consumedAmount",
            "type": "number",
            "format": ""
        },
        {
            "name": "usagePercentage",
            "baseName": "usagePercentage",
            "type": "number",
            "format": ""
        },
        {
            "name": "hasAccess",
            "baseName": "hasAccess",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "remainingAmount",
            "baseName": "remainingAmount",
            "type": "number",
            "format": ""
        },
        {
            "name": "exceededAmount",
            "baseName": "exceededAmount",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductConsumption.attributeTypeMap;
    }

    public constructor() {
    }
}
