/**
 * Vayu API
 * The Vayu API is a RESTful API that allows you to submit events for processing and storage & manage billing related entities.           The API is secured using the Bearer Authentication scheme with JWT tokens.           To obtain a JWT token, please contact Vayu at team@withvayu.com
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@withvayu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Event } from '../models/Event';
import { InvalidEvent } from '../models/InvalidEvent';
import { HttpFile } from '../http/http';

export class SendEventsResponse {
    /**
    * An array of events that were successfully processed and sent to the queue.
    */
    'validEvents': Array<Event>;
    /**
    * An array of events that failed validation and were not sent to the queue. Each object contains the event and the error message.
    */
    'invalidEvents': Array<InvalidEvent>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "validEvents",
            "baseName": "validEvents",
            "type": "Array<Event>",
            "format": ""
        },
        {
            "name": "invalidEvents",
            "baseName": "invalidEvents",
            "type": "Array<InvalidEvent>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SendEventsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

